# Generated by Django 3.2.25 on 2024-09-10 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_recommender', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
